displayName=Thrall Highlighter
author=sung-rai
description=Hightlights, and optionally hides thralls.
tags=thrall, hide, outline, highlight, visual
version=1.0.0
plugins=com.thrallHighlighter.thrallHighlighterPlugin
build=standard