displayName=Thrall Highlighter
author=sung-rai
description=Highlights, and optionally hides thralls.
tags=thrall, hide, outline, highlight, visual
version=1.0.1
plugins=com.thrallHighlighter.thrallHighlighterPlugin
build=standard
